### ISSUE TITLE
The version on luarocks is missing `init.lua`

### ISSUE THREAD

**Issue by crispinha** [lovetoys/lovetoys#78]
I'm using plain luarocks not loverocks (it dosen't seem to be compatible with my lua/rocks version) and I'm on Arch Linux with love and luarocks installed through my distro package manager
I run `luarocks install --tree deps lovetoys` to install it in the deps subdirectory of my working folder, which makes [this file tree](https://gist.github.com/crispinha/d528b44b4879e973f4a8e17f30427171). If I then set my lua path to include `./deps` and run `love .` with a `main.lua` that has `require deps/lovetoys` I get [this traceback](https://gist.github.com/crispinha/1b319b320534f8bbedfb18fbac15ca7b), which is looking for `.../lovetoys/init.lua`, which exists in the git repo. If I download [the release version](https://github.com/lovetoys/lovetoys/releases/tag/v0.4.0) then I can get that importing but then I get #77 (but that indicates that lovetoys is importing properly)

I might have a kinda weird setup, as I haven't worked with Lua before and so I'm just now getting my whole lua environment set up.

**Comment by raffomania** [comment]
This seems related to the fixes i pushed for #77 - I'll install the rock myself and see what I can do. In the meanwhile, you can download the tarball from the latest commit instead of the last release to get it to work :)

**Comment by crispinha** [comment]
Yeah - the tarball & submodule work fine, but then that has all the packaging/examples and not just the library.

Thanks for looking into it :)

**Comment by vaartis** [comment]
The 0.4.0-1 version from luarocks still doesn't work, same error.

**Comment by Nukesor** [comment]
A little late to the party, but a new version on luarocks has just been released :)
